# Lab 10.01 : Convolutional layer - demo

In [1]:
import torch
import torch.nn as nn

### Make a convolutional module
* inputs:  2 channels
* output:  5 activation maps 
* filters are 3x3
* padding with one layer of zero to not shrink anything

In [2]:
mod = nn.Conv2d( 2 , 5 ,  kernel_size=3,  padding=1 )

### Make an input 2 x 6 x 6  (two channels, each one has 6 x 6 pixels )

In [3]:
bs=1

x=torch.rand(bs,2,6,6)

print(x)

tensor([[[[0.7181, 0.8568, 0.0340, 0.6575, 0.1105, 0.0676],
          [0.1058, 0.9462, 0.6928, 0.1851, 0.8249, 0.6068],
          [0.9668, 0.6312, 0.0397, 0.9596, 0.0154, 0.4954],
          [0.6873, 0.5906, 0.5622, 0.7808, 0.4852, 0.7338],
          [0.6976, 0.0188, 0.2101, 0.4038, 0.2028, 0.7788],
          [0.6959, 0.1166, 0.3629, 0.0573, 0.1831, 0.6494]],

         [[0.3348, 0.6391, 0.2354, 0.2884, 0.0911, 0.6898],
          [0.4198, 0.0400, 0.3542, 0.9015, 0.3991, 0.0029],
          [0.9608, 0.6041, 0.1153, 0.1647, 0.0654, 0.4545],
          [0.6076, 0.9211, 0.8045, 0.4389, 0.9410, 0.3615],
          [0.4944, 0.6257, 0.9751, 0.3753, 0.9210, 0.4607],
          [0.2794, 0.3802, 0.0463, 0.6358, 0.4628, 0.6392]]]])


### Feed it to the convolutional layer: the output should have 5 channels (each one is 6x6)

In [4]:
y=mod(x)

print(y)

tensor([[[[ 0.0950, -0.0222,  0.2814,  0.1918,  0.1607,  0.1400],
          [ 0.4557,  0.7871,  0.5395,  0.2820,  0.4214,  0.4022],
          [ 0.1361,  0.5293,  0.7309,  0.5272,  0.7420,  0.4905],
          [ 0.3607,  0.5200,  0.5835,  0.2141,  0.5204,  0.3304],
          [ 0.2671,  0.6377,  0.3960,  0.5596,  0.4748,  0.4991],
          [ 0.2439,  0.5019,  0.3449,  0.3135,  0.4734,  0.2963]],

         [[-0.3155, -0.4418, -0.2179, -0.0805, -0.1021, -0.1605],
          [-0.3865, -0.1475, -0.3887, -0.4216, -0.1672, -0.1586],
          [-0.7149, -0.1579, -0.1094, -0.4234, -0.0819, -0.1469],
          [-0.6867, -0.4072, -0.1451, -0.3148, -0.3689, -0.0114],
          [-0.5861, -0.2939, -0.3605, -0.1900, -0.4118, -0.0066],
          [-0.3493, -0.2604, -0.1719, -0.2952, -0.2374, -0.1628]],

         [[-0.0399,  0.0976, -0.1810, -0.1335, -0.0367, -0.1062],
          [ 0.1072, -0.0519,  0.0424,  0.1927, -0.0574,  0.0341],
          [ 0.1835,  0.3113, -0.0952, -0.0150,  0.0540, -0.0502],
      

### Lets look at the 5 filters.
* Our filters are 2x3x3
* Each of the filter has 2 channels because the inputs have two channels

In [5]:
mod.weight

Parameter containing:
tensor([[[[ 0.2357,  0.1336,  0.2168],
          [ 0.1196,  0.0283,  0.1189],
          [ 0.1463, -0.0218, -0.1337]],

         [[ 0.0624,  0.0546,  0.0244],
          [-0.0141, -0.1933, -0.0707],
          [-0.0003,  0.1563, -0.1452]]],


        [[[-0.0727, -0.0146, -0.0165],
          [-0.0714, -0.1640, -0.0308],
          [ 0.0509, -0.1349, -0.0065]],

         [[ 0.0775, -0.0645, -0.0701],
          [ 0.2238, -0.1962, -0.1409],
          [ 0.1251,  0.1151, -0.1658]]],


        [[[-0.0476,  0.2242,  0.1777],
          [ 0.0165,  0.0593, -0.1151],
          [-0.1122,  0.0237,  0.0610]],

         [[-0.0220,  0.0428, -0.0252],
          [ 0.1824,  0.1212,  0.0748],
          [-0.0771, -0.0614, -0.0907]]],


        [[[-0.2063,  0.1406,  0.0474],
          [-0.0137,  0.0851,  0.1619],
          [ 0.2096,  0.1427, -0.2184]],

         [[ 0.0070, -0.1709, -0.2185],
          [-0.0944, -0.1351,  0.0646],
          [-0.2073,  0.0838, -0.0035]]],


        [[[-0.0007